[package]
name = "pond-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
duckdb = { version = "^1.0.0", features = ["bundled"] }
sha2 = "0.10.8"
regex = "1.11.0"
thiserror = "1.0.64"
lazy_static = "1.5.0"
sqlparser = "0.51.0"
