name: SLSA
on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      digests: ${{ steps.hash.outputs.digests }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Build Lambda functions
        run: |
          cd pond
          cargo build --release
          # Assuming your Lambda binaries are in target/release
          cp target/release/pond-planner ../pond-planner
          cp target/release/pond-duckling ../pond-duckling

      - name: Generate subject for provenance
        id: hash
        run: |
          set -euo pipefail
          files="pond-planner pond-duckling"
          echo "digests=$(sha256sum $files | base64 -w0)" >> "${GITHUB_OUTPUT}"

  provenance:
    needs: [build]
    permissions:
      actions: read
      id-token: write
      contents: write
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v1.4.0
    with:
      base64-subjects: "${{ needs.build.outputs.digests }}"
      upload-assets: true
